### ISSUE TITLE
macOS is not supported

### ISSUE THREAD

**Issue by ivabus** [thm-unix/count#2]
### Affected version
v.0.1

### Description
No Settings, Exit, About entries in status bar.

### Steps to reproduce
1. Open the application
2. Open File menu in status bar

### Frequency of reproducing
Always

**Comment by ivabus** [comment]
Закрыто по причине доббаёб

**Comment by ivabus** [comment]
Открыто по причине долбаёб х2

**Comment by ivabus** [comment]
Закрыто по причине долбаёб х3

**Comment by thm-unix** [comment]
macOS and Windows support will be added in next releases.

**Comment by thm-unix** [comment]
macOS and Windows support will be added in next releases.

**Comment by thm-unix** [comment]
macOS and Windows support will be added in next releases.

**Comment by thm-unix** [comment]
macOS and Windows support will be added in next releases.

**Comment by thm-unix** [comment]
Offical macOS and Windows support will be added in further releases.
